# Generated by Django 5.0.4 on 2024-04-24 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_alter_shoe_production_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='production_date',
            field=models.DateField(),
        ),
    ]
