# Generated by Django 5.0.4 on 2024-04-27 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0004_discription_shoe_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discription',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
