# Generated by Django 5.0.4 on 2024-04-27 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0009_remove_size_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='range',
            field=models.IntegerField(),
        ),
    ]
