# Generated by Django 5.0.4 on 2024-04-29 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0012_kind_shoe_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='size',
            name='range',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='size',
        ),
        migrations.AddField(
            model_name='shoe',
            name='size',
            field=models.ManyToManyField(to='shoes.size'),
        ),
    ]
