# Generated by Django 5.0.4 on 2024-05-01 14:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0013_size_range_remove_shoe_size_shoe_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discription',
            name='name',
            field=models.CharField(max_length=100, verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='name',
            field=models.CharField(max_length=50, verbose_name='جنس رویه'),
        ),
        migrations.AlterField(
            model_name='kind',
            name='slug',
            field=models.SlugField(default='', verbose_name='اسلاگ در url'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='brand',
            field=models.CharField(max_length=30, verbose_name='برند'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='color',
            field=models.CharField(max_length=30, verbose_name='رنگ'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='discription',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.discription', verbose_name='توضیح'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='gender',
            field=models.CharField(max_length=10, verbose_name='جنسیت'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='kind',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.kind', verbose_name='جنس رویه'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='photo',
            field=models.ImageField(upload_to='files/shoes', verbose_name='عکس'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='قیمت'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='property',
            field=models.CharField(max_length=30, verbose_name='ویژگی'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='size',
            field=models.ManyToManyField(to='shoes.size', verbose_name='اندازه'),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='slug',
            field=models.SlugField(default='', verbose_name='اسلاگ در url'),
        ),
        migrations.AlterField(
            model_name='size',
            name='range',
            field=models.IntegerField(blank=True, null=True, verbose_name='اندازه'),
        ),
    ]
