# Generated by Django 5.0.4 on 2024-05-18 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0018_remove_shoe_cart_alter_kind_slug_delete_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='slug',
            field=models.CharField(db_index=True, default='', max_length=50, verbose_name='اسلاگ در url'),
        ),
    ]
