# Generated by Django 5.0.4 on 2024-05-20 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0023_date_remove_cartitem_cart_remove_cartitem_shoe_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='name',
        ),
    ]
