# Generated by Django 5.0.4 on 2024-05-20 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0024_remove_date_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='date',
            name='price',
        ),
    ]
