# Generated by Django 5.0.4 on 2024-05-21 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0025_remove_date_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='date',
            name='name',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
