# Generated by Django 5.0.4 on 2024-05-21 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0028_date_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='created_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
