# Generated by Django 5.0.4 on 2024-05-21 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0029_alter_date_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='date',
            name='created_at',
            field=models.DateTimeField(default='2/3/2022', null=True),
        ),
    ]
