# Generated by Django 5.0.4 on 2024-05-22 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0031_remove_shoe_date_shoe_created_at_pashneboland_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='created_at',
            field=models.DateTimeField(default='YYYY-MM-DD HH:MM[:ss[.uuuuuu]][TZ] ', null=True, verbose_name='تاریخ تولید'),
        ),
    ]
