# Generated by Django 5.0.4 on 2024-05-22 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0033_alter_shoe_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='created_at',
            field=models.DateField(null=True, verbose_name='تاریخ تولید'),
        ),
    ]
