# Generated by Django 5.0.4 on 2024-05-22 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0034_alter_shoe_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pashneboland',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='created_at',
        ),
    ]
