# Generated by Django 5.0.4 on 2024-05-22 13:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0035_remove_pashneboland_created_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, verbose_name='برند')),
                ('property', models.CharField(max_length=30, verbose_name='ویژگی')),
                ('color', models.CharField(max_length=30, verbose_name='رنگ')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('photo', models.ImageField(upload_to='files/shoes', verbose_name='عکس')),
                ('gender', models.CharField(max_length=10, verbose_name='جنسیت')),
                ('slug', models.CharField(db_index=True, default='', max_length=50, verbose_name='اسلاگ در url')),
                ('discription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.discription', verbose_name='توضیح')),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.kind', verbose_name='جنس رویه')),
                ('size', models.ManyToManyField(to='shoes.size', verbose_name='اندازه')),
            ],
            options={
                'verbose_name': 'پاشنه بلند',
                'verbose_name_plural': 'پاشنه بلندها',
            },
        ),
        migrations.CreateModel(
            name='Catooni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=30, verbose_name='برند')),
                ('property', models.CharField(max_length=30, verbose_name='ویژگی')),
                ('color', models.CharField(max_length=30, verbose_name='رنگ')),
                ('price', models.IntegerField(blank=True, null=True, verbose_name='قیمت')),
                ('photo', models.ImageField(upload_to='files/shoes', verbose_name='عکس')),
                ('gender', models.CharField(max_length=10, verbose_name='جنسیت')),
                ('slug', models.CharField(db_index=True, default='', max_length=50, verbose_name='اسلاگ در url')),
                ('discription', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.discription', verbose_name='توضیح')),
                ('kind', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shoes.kind', verbose_name='جنس رویه')),
                ('size', models.ManyToManyField(to='shoes.size', verbose_name='اندازه')),
            ],
            options={
                'verbose_name': 'پاشنه بلند',
                'verbose_name_plural': 'پاشنه بلندها',
            },
        ),
    ]
