# Generated by Django 5.0.4 on 2024-05-22 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0038_boot_date_catooni_date_pashneboland_date_shoe_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boot',
            name='date',
            field=models.DateField(default='2-3-2022', null=True),
        ),
        migrations.AlterField(
            model_name='catooni',
            name='date',
            field=models.DateField(default='2-3-2022', null=True),
        ),
        migrations.AlterField(
            model_name='pashneboland',
            name='date',
            field=models.DateField(default='2-3-2022', null=True),
        ),
        migrations.AlterField(
            model_name='shoe',
            name='date',
            field=models.DateField(default='2-3-2022', null=True),
        ),
    ]
