# Generated by Django 5.0.4 on 2024-05-22 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0039_alter_boot_date_alter_catooni_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boot',
            name='date',
        ),
        migrations.RemoveField(
            model_name='catooni',
            name='date',
        ),
        migrations.RemoveField(
            model_name='pashneboland',
            name='date',
        ),
        migrations.RemoveField(
            model_name='shoe',
            name='date',
        ),
    ]
