# Generated by Django 5.0.4 on 2024-05-23 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0041_shoe_my_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='my_date',
            field=models.DateField(default='2_3_2022', null=True),
        ),
    ]
