# Generated by Django 5.0.4 on 2024-05-23 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0043_alter_shoe_my_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='my_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
