# Generated by Django 5.0.4 on 2024-05-23 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0044_alter_shoe_my_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shoe',
            name='my_date',
        ),
    ]
