# Generated by Django 5.0.4 on 2024-05-23 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0045_remove_shoe_my_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catooni',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='catooni',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='catooni',
            name='size',
        ),
        migrations.RemoveField(
            model_name='pashneboland',
            name='discription',
        ),
        migrations.RemoveField(
            model_name='pashneboland',
            name='kind',
        ),
        migrations.RemoveField(
            model_name='pashneboland',
            name='size',
        ),
        migrations.DeleteModel(
            name='Boot',
        ),
        migrations.DeleteModel(
            name='Catooni',
        ),
        migrations.DeleteModel(
            name='Pashneboland',
        ),
    ]
